runtime: python311 # or another supported version

instance_class: F2

env_variables:
  BUCKET_NAME: myprofile

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /image
  static_dir: static/image

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
