runtime: nodejs18 # Atur sesuai dengan versi Node.js yang sesuai dengan aplikasi Anda

instance_class: F2

env_variables:
  BUCKET_NAME: myprofile

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /style.css
  static_files: static/style.css
  upload: static/style.css

- url: /image
  static_dir: static/image

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
