runtime: Node.js v18.18.0 # or another supported version

instance_class: F2

env_variables:
  BUCKET_NAME: myprofile

handlers:
- url: /
  static_files: /index.html
  upload: /index.html

  - url: /
  static_files: /style.css
  upload: /style.css

- url: /image
  static_dir: static/image

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
